version: '3.1'

services:

  database:
    image: postgres
    ports:
      - 5432:5432

  cassandra00:
    build: ./cassandra
    ports: 
      - '7000:7000'
      - '7001:7001'
      - '7199:7199'
      - '9042:9042'
      - '9160:9160'
      - '9404:9404'
    environment:
        CASSANDRA_KEYSPACE: "shippy"
        CASSANDRA_START_RPC: "true"
        CASSANDRA_BROADCAST_ADDRESS: "127.0.0.1"
        CASSANDRA_RPC_ADDRESS: "127.0.0.1"
        CASSANDRA_LISTEN_ADDRESS: "127.0.0.1"

  datastore:
    image: mongo
    ports:
      - 27017:27017
      
  api:
      build: ./api
      ports:
        - 8080:8080
      environment:
          MICRO_ADDRESS: ":8080"
          MICRO_REGISTRY: "mdns"
          MICRO_API_HANDLER: "rpc"
          MICRO_NAMESPACE: "shippy"
          CORS_ALLOWED_METHODS: "POST"
          CORS_ALLOWED_ORIGINS: "http://localhost:3000" 
          #CORS_ALLOWED_HEADERS: "Content-Type, Access-Control-Allow-Origin"

  #consignment-cli:
    #build: ./consignment-cli
    #environment:
      #MICRO_REGISTRY: "mdns"

  #user-cli:
    #build: ./user-cli
    #environment:
      #MICRO_REGISTRY: "mdns"

  email-service:
    build: ./email-service
    ports:
      - 50054:50051
    environment:
      MICRO_ADDRESS: ":50051"
      MICRO_REGISTRY: "mdns"


  consignment-service:
    build: ./consignment-service
    ports:
      - 50051:50051
    environment:
      MICRO_ADDRESS: ":50051"
      MICRO_REGISTRY: "mdns"
      DB_HOST: "datastore:27017"

  vessel-service:
    build: ./vessel-service
    ports:
     - 50052:50051
    environment:
      MICRO_ADDRESS: ":50051"
      MICRO_REGISTRY: "mdns"
      DB_HOST: "datastore:27017"

  user-service:
    build: ./user-service
    ports:
      - 50053:50051
    environment:
      MICRO_ADDRESS: ":50051"
      MICRO_REGISTRY: "mdns"
      DB_NAME: "postgres"
      DB_HOST: "172.0.0.1"
      DB_PORT: "9160"
      DB_USER: "postgres"
      DB_PASSWORD: "postgres"
    #depends_on:
      #- cassandra00
      